language: python
python:
  - "3.8"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install numpy scipy scikit-learn matplotlib h5py netCDF4 cartopy

script:
  - pytest tests/*
