language: python
python:
  - "3.8"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - conda config --add channels conda-forge
  - conda env create --file=environment.yml
  - conda activate pygtm-env

script:
  - pytest tests/*
