language: python
python:
  - "3.8"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda --quiet
  - conda config --add channels conda-forge

install:
  - conda env create --file=environment.yml
  - conda activate pygtm-env

script:
  - pytest tests/*
