language: python
python:
  - "3.8"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - conda env create --file=environment.yml
  - conda activate pygtm-env

script:
  - pytest tests/*
